package: connectomix
title: Connectivity report for participant '{subject}'
sections:
- name: Connectivity
  reportlets:
  - bids:
      datatype: figures
      extension: [.svg]
      suffix: matrix
    caption: Connectivity matrix
